### ISSUE TITLE
composer install dà errore se si accettano tutti i valori di difetto

### ISSUE THREAD

**Issue by simevo** [damikael/spid-php#1]
su debian buster con [composer 1.6.5](https://packages.debian.org/buster/composer):
```
In Setup.php line 73:
                                        
  symlink(): No such file or directory  
```

in effetti sta cercando di creare un link da `/home/paolog/Sviluppo/teamdigitale/spid-php/vendor/simplesamlphp/simplesamlphp/www` a: `-e /home/paolog/public_html/myservice`

c'è qualcosa di sbagliato qui:
https://github.com/damikael/spid-php/blob/master/setup/Setup.php#L18

**Comment by damikael** [comment]
Risolto con le ultime commit
