### ISSUE TITLE
necessario creare il "path for www"

### ISSUE THREAD

**Issue by simevo** [damikael/spid-php#2]
questo andrebbe documentato nel README, es. per far sì che funzioni con i valori di difetto:
```
mkdir -p "$HOME/public_html"
```

**Comment by damikael** [comment]
Risolto con le ultime commit.
Se il path non esiste tenta di crearlo automaticamente. In tal caso viene mostrato l'avviso:

_Webroot directory not found. Making directory .../public_html
Please remember to configure your virtual host._
